# Generated by Django 5.1.4 on 2025-05-09 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_alter_plan_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='stock_coverage',
        ),
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('SUPER_PREMIUM', 'Super Premium'), ('FREE_TRIAL', 'free_trial')], max_length=30),
        ),
    ]
