# Generated by Django 5.1.4 on 2025-05-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0004_remove_plan_stock_coverage_alter_plan_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='stock_coverage',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
