# Generated by Django 5.1.4 on 2025-05-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_plan_stock_coverage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='name',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('PREMIUM', 'Premium'), ('SUPER_PREMIUM', 'Super Premium')], max_length=30),
        ),
        migrations.AlterField(
            model_name='plan',
            name='stock_coverage',
            field=models.PositiveIntegerField(),
        ),
    ]
